config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'homes#index'
  resources :homes do
    collection do
      get 'about'
      get 'howto'
    end
  end
  resources :tasks
  
  resources :homeworks do
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:show, :edit, :update, :destroy]

  def index
    @task = current_user.tasks.all
  end

  def show
  end

  def edit
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to tasks_path, notice: '作成できました'
    else
      render :new, alert: '作成できませんでした'
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: '更新できました'
    else
      render :show, alert: '更新できませんでした'
    end
  end

  def destroy
    if @task.destroy
      redirect_to tasks_path, notice: '削除しました'
    else
      redirect_to tasks_path, alert: '削除に失敗しました'
    end
  end

  def about
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :body, :deadline)
    end

    def validate_user
      if @task.user != current_user
        redirect_to root_path, alert: "自分のタスクではありません"
      end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<div class = "container">
    <%= form_for(@task) do |f| %>
        <div class = "card container pt-3">
            <div class = "form-group">
                <%= f.label 'タイトル'%>
                <%= f.text_field :title, class: 'form-control'%>
            </div>

            <div class = "form-group">
                <%= f.label '内容'%>
                <%= f.text_field :body, class: 'form-control'%>
            </div>

            <div class = "form-group">
                <%= f.label '締め切り'%>
                <%= f.date_select :deadline, use_month_numbers:true, prompt:"--", class: 'form-control'%>
            </div>
            
        </div>

        <%= f.submit "更新",class:'btn btn-success float-right mt-3'%>
    <%end%>
</div>

app/views/tasks/index.html.erb
<% if user_signed_in? %>
    <h2 class ="text-center">[Todoリスト]</h2>

    <div class = "container">
    <div class ="table-responsive text-nowrap">
        <%= link_to "新規作成", new_task_path, class: "btn btn-primary float-right mb-2" %>
        <table class = "table table-bordered text-center">
            <thead class = "thead-light">
                <tr>
                    <th>タイトル</th>
                    <th>内容</th>
                    <th>締切</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @task.each do |task| %>
                    <tr>
                        <td><%= task.title %></td>
                        <td><%= task.body %></td>
                        <td><%= task.deadline %></td>
                        <td><%= link_to '',  task, class: 'fas fa-edit fa-2x text-dark'%></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    </div>
<%end%>

app/views/tasks/new.html.erb
<div class = "container mt-3">
    <div class ="col-md-8 mx-auto">
    <%= form_for(@task) do |f| %>
        <div class = "card container pt-3">
            <div class ="form-group">
                <div class = "form-group row">
                    <%= f.label 'タイトル：', class: 'col-md-2'%>
                    <%= f.text_field :title, class: 'form-control col-md-6'%>
                </div>

                <div class = "form-group row">
                    <%= f.label '内容：', class: 'col-md-2'%>
                    <%= f.text_field :body, class: 'form-control col-md-6'%>
                </div>

                <div class = "form-group row">
                    <%= f.label '締め切り：', class: 'col-md-2'%>
                    <%= f.date_select :deadline, use_month_numbers:true, prompt:"--", start_year:Time.now.year, class: 'form-control col-md-6'%>
                </div>
                </div>
        </div>

        <%= f.submit "タスク登録",class:'btn btn-success float-right mt-3'%>
    <%end%>
    </div>
</div>

app/views/tasks/show.html.erb
<div class = "col-md-6 mx-auto px-3 py-2">
<ul class = "h5" style ="line-height:2.5rem;">
    <li> タイトル：<%= @task.title %></li>
    <li> 内容：<%= @task.body%></li>
    <li>締切：<%= @task.deadline%></li>
</ul>

    <%= link_to "削除", task_path(@task), method: :delete, data: {confirm: "本当に削除しますか？"}, class: 'btn btn-danger float-right mt-3'%>
    <%= link_to "編集", edit_task_path, class: 'btn btn-success float-right mt-3 mx-3'%>
</div>