config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'homes#index'
  resources :homes do
    collection do
      get 'about'
      get 'howto'
    end
  end
  resources :tasks
  
  resources :homeworks do
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_login.html.erb
        <%= image_tag "#{current_user.course.course_name}summer.jpg", class: 'w-100'%>
<div class ="container">
    <div class = "row">

        <div class = "col-sm-12 col-md-6 mt-5">
            <h2 class ="text-center text-white bg-danger rounded-top py-2 mb-0">本日提出の課題</h2>
            <table class = "table table-bordered">

                <thead class = "thead-light">
                    <tr>
                        
                        <th>教科</th>
                        <th>課題内容</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                <% current_user.course.homeworks.all.each do |homework| %>
                    <tr>
                    <% if Date.today == homework.deadline %>
                        <td><%= homework.subject %></td>
                        <td><%= homework.content %></td>
                        <td><%= link_to '',  homework, class: 'fas fa-edit fa-2x text-dark'%></td>
                    <% end %>
                    <tr>
                <% end %>
                </tbody>

            </table>
                </div>
        <div class = "col-sm-12 col-md-6 mt-5">
                <h2 class ="text-center text-white bg-danger rounded-top py-2 mb-0">本日提出のタスク</h2>
                <table class = "table table-bordered">

                    <thead class = "thead-light">
                        <tr>
                            
                            <th>タイトル</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                    <% current_user.tasks.all.each do |task| %>
                        <tr>
                        <% if Date.today == task.deadline %>
                            <td><%= task.title %></td>
                            <td><%= link_to '',  task, class: 'fas fa-edit fa-2x text-dark'%></td>
                        <% end %>
                        <tr>
                    <% end %>
                    </tbody>

                </table>
            </div>
        </div>

    </div>
    </div>

    

app/views/homes/_not-login.html.erb
<%= image_tag "top-bg.png", class: 'w-100 mx-auto mb-3'%>

<div class ="container">
    <div class ="d-none d-md-block">
    <div class ="my-5 col-md-8 col-sm-12 mx-auto">
        <i class="fas fa-school fa-3x bg-dark rounded-circle p-3 text-white d-inline"></i>
        <h2 class ="d-inline">クラスのみんなで課題を共有しよう！</h2>
    </div>
    </div>

    <div class ="row pt-5">
        <div class ="col-md-4">
            <div class = "text-center">
            <i class="fas fa-user-shield fa-3x bg-dark rounded-circle p-3 text-white text-center"></i>
            <h3>個人タスク機能</h3>
            <p>ユーザー個人のタスク管理機能も搭載。<br>
                課題以外のタスクもこのサイトでまとめて見ることができます。</p>
            </div>
        </div>
        <div class ="col-md-4">
            <div class ="text-center">
            <i class="fas fa-id-card fa-3x bg-dark rounded-circle p-3 text-white"></i>
            <h3>全コース対応！</h3>
            <p>５学年×４コースに完全対応。
            ユーザー登録時に自分の所属しているクラスをお選びください</p>
            </div>
        </div>
        <div class ="col-md-4">
            <div class ="text-center">
            <i class="fas fa-eye fa-3x bg-dark rounded-circle p-3 text-white"></i>
            <h3>時間割も見れる！</h3>
            <p>見やすくわかりやすい時間割を<br>Topページで確認できます。<br>
                (M科の方にご協力いただきました。)</p>
            </div>
        </div>
    </div>

    <div class = "col-md-6 card mx-auto p-0 mt-5">
        <div class ="card-header text-center bg-dark">
            <h2 class ="text-light">新規登録はこちら</h2>
            <%= link_to 'サインアップ', new_user_registration_path, class: 'btn bg-white text-dark' %>
        </div>

        <div class ="card-body text-center">

            <h3>登録済みの方はこちらから</h3>
            <%= link_to 'ログイン', new_user_session_path, class: 'btn bg-dark text-white' %>
        </div>
    </div>
</div>

app/views/homes/about.html.erb
<div class = "col-md-10 mx-auto bg-light pt-3" style ="line-height:2rem;">
<h1 class = "text-center pb-2"><strong>利用規約</strong></h1>
この利用規約（以下，「本規約」といいます。）は，運営がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
<br><br>
<h2><strong>第1条（適用）</strong></h2>
<ol>
<li>本規約は，ユーザーと運営との間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
<li>運営は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。</li>
<li>本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</li>
</ol>
<br><br>
<h2><strong>第2条（利用登録）</strong></h2>第2条（利用登録）
<ol>
<li>本サービスにおいては，登録希望者が本規約に同意の上，運営の定める方法によって利用登録を申請し，運営がこれを承認することによって，利用登録が完了するものとします。</li>
<li>運営は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</li>
<ol>
<li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
<li>本規約に違反したことがある者からの申請である場合</li>
<li>その他，運営が利用登録を相当でないと判断した場合</li>
</ol>
</ol>
<br><br>
<h2><strong>第3条（ユーザーIDおよびパスワードの管理）</strong></h2>
<ol>
<li>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</li>
<li>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。運営は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
<li>ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，運営に故意又は重大な過失がある場合を除き，運営は一切の責任を負わないものとします。</li>
</ol>
<br><br>
<h2><strong>第4条（利用料金および支払方法）</strong></h2>
<ol>
<li>ユーザーは，本サービスの有料部分の対価として，運営が別途定め，本ウェブサイトに表示する利用料金を，運営が指定する方法により支払うものとします。</li>
<li>ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。</li>
</ol>
<br><br>
<h2><strong>第5条（禁止事項）</strong></h2>
ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。
<ol>
<li>法令または公序良俗に違反する行為</li>
<li>犯罪行為に関連する行為</li>
<li>本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為</li>
<li>運営，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
<li>本サービスによって得られた情報を商業的に利用する行為</li>
<li>運営のサービスの運営を妨害するおそれのある行為</li>
<li>不正アクセスをし，またはこれを試みる行為</li>
<li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
<li>不正な目的を持って本サービスを利用する行為</li>
<li>本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為</li>
<li>他のユーザーに成りすます行為</li>
<li>運営が許諾しない本サービス上での宣伝，広告，勧誘，または営業行為</li>
<li>面識のない異性との出会いを目的とした行為</li>
<li>運営のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
<li>その他，運営が不適切と判断する行為</li>
</ol>
<br><br>
<h2><strong>第6条（本サービスの提供の停止等）</strong></h2>
<ol>
<li>運営は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</li>
<ol>
<li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
<li>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
<li>コンピュータまたは通信回線等が事故により停止した場合</li>
<li>その他，運営が本サービスの提供が困難と判断した場合</li>
</ol>
<li>運営は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</li>
</ol>
<br><br>
<h2><strong>第7条（利用制限および登録抹消）</strong></h2>
<ol>
<li>運営は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。</li>
<ol>
<li>本規約のいずれかの条項に違反した場合</li>
<li>登録事項に虚偽の事実があることが判明した場合</li>
<li>料金等の支払債務の不履行があった場合</li>
<li>運営からの連絡に対し，一定期間返答がない場合</li>
<li>本サービスについて，最終の利用から一定期間利用がない場合</li>
<li>その他，運営が本サービスの利用を適当でないと判断した場合</li>
</ol>
<li>運営は，本条に基づき運営が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
</ol>
<br><br>
<h2><strong>第8条（退会）</strong></h2>
ユーザーは，運営の定める退会手続により，本サービスから退会できるものとします。
<br><br>
<h2><strong>第9条（保証の否認および免責事項）</strong></h2>
<ol>
<li>運営は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
<li>運営は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する運営とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</li>
<li>前項ただし書に定める場合であっても，運営は，運営の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（運営またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，運営の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</li>
<li>運営は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
</ol>
<br><br>
<h2><strong>第10条（サービス内容の変更等）</strong></h2>
運営は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。
<br><br>
<h2><strong>第11条（利用規約の変更）</strong></h2>
運営は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。
<br><br>
<h2><strong>第12条（個人情報の取扱い）</strong></h2>
運営は，本サービスの利用によって取得する個人情報については，運営「プライバシーポリシー」に従い適切に取り扱うものとします。
<br><br>
<h2><strong>第13条（通知または連絡）</strong></h2>
ユーザーと運営との間の通知または連絡は，運営の定める方法によって行うものとします。運営は,ユーザーから,運営が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。
<br><br>
<h2><strong>第14条（権利義務の譲渡の禁止）</strong></h2>
ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。
</div>

<footer class ="bg-dark">
    <div class ="container">
      <div class ="col-md-6 mx-auto text-white pb-5 pt-3 mt-3">
        <li>
          <%= link_to '利用規約', about_homes_path, class: 'text-white pr-3'%>
        </li>
        <% if current_user.try(:admin?) %>
          <li>
            <%= link_to '管理者ページ', rails_admin_path, class: 'text-white pr-3'%>
          </li>
        <% end %>
        <li>
          お問い合わせはTwitterのDMまで
        </li>
        <a href = "https://twitter.com/mkrms_again" class="fab fa-twitter-square fa-3x text-white float-right"></a>
      </div>
        <p class ="text-center text-white">Niiyama keisuke</p>
    </div>
  </footer>

app/views/homes/howto.html.erb
<div class = "col-md-10 mx-auto bg-light pt-3" style ="line-height:2rem;">
<h1 class = "text-center pb-2"><strong>使い方</strong></h1>
<h2>新規ユーザー登録、もしくはログインをする。</h2>
<ol>
<li>ヘッダーのサインアップ、ログインのボタンから新規登録画面、ログイン画面に進む。(スマホの方は右上のメニューボタンをタップ)</li>
<li>学籍番号(半角英数字)・クラス・メールアドレス・パスワード(６文字以上)を入力し、新規ユーザー登録ボタンをクリック。</li>
</ol>
<ul>
<li>ログインの際は学籍番号とパスワードのみでログインできます。</li>
</ul>

<h2>Top画面</h2>
<ul>
<li>トップ画面上部には、それぞれのコースに対応した時間割が表示されています。(表示されない場合は再読み込みをお願いします。)</li>
<li>トップ画面下部には、「本日提出の課題」・「本日締切のタスク」の両方が表示され、ひと目で当日締切の課題やタスクを確認することができます。</li>
</ul>

<h2>課題管理</h2>
<ol>
<li>ヘッダーの課題管理をクリック(スマホの方は右上のメニューボタンをクリック)</li>
<li>新規登録ボタンをクリック</li>
<li>教科・課題内容・締切・説明文を入力し「課題登録」ボタンをクリック</li>
<li>課題一覧のページに登録されていることが確認できます。</li>
</ol>

<ul>
<li>課題一覧・締切前・締切超過のそれぞれのボタンを押すと、登録された課題の締切に応じた箇所に表示されていることが確認できます。</li>
<li>締切に応じて日付の文字が、締切前「黒」・締切当日「緑」・締切超過「赤」で表示されます。</li>
<li><i class = 'fas fa-edit text-dark'></i>のアイコンをクリックすると課題詳細ページが表示されます。</li>

<li>課題詳細ページでは、課題を登録したユーザーのみ編集、削除が可能です。それぞれのボタンをクリックしてお進みください。</li>
<li>課題詳細ページでは、すべてのユーザーが課題に対してコメントすることができます。コメントはコメントを投稿したユーザーのみ削除ができます。</li>
</ul>

<ul>
<li>課題管理機能は同じクラスの人であれば登録された課題を閲覧できるようなシステムとなっております。クラスのみんなで充実したManagerにつくりあげていきましょう！</li>
</ul>

<h2>Todoリスト</h2>
<ol>
<li>ヘッダーのTodoをクリック(スマホの方は右上のメニューボタンをクリック)</li>
<li>新規登録ボタンをクリック</li>
<li>タイトル・内容・締切を入力し「タスク登録」ボタンをクリック</li>
<li>Todo一覧のページに登録されていることが確認できます。</li>
</ol>

<ul>
<li>Todoリスト機能は他のユーザーに見られないプライベートなシステムとなっております。個人的なタスクだから課題管理の方には書けないな…などといったタスクを管理するときにおすすめです。</li>
</ul>
</div>

<footer class ="bg-dark">
    <div class ="container">
      <div class ="col-md-6 mx-auto text-white pb-5 pt-3 mt-3">
        <li>
          <%= link_to '利用規約', about_homes_path, class: 'text-white pr-3'%>
        </li>
        <% if current_user.try(:admin?) %>
          <li>
            <%= link_to '管理者ページ', rails_admin_path, class: 'text-white pr-3'%>
          </li>
        <% end %>
        <li>
          お問い合わせはTwitterのDMまで
        </li>
        <a href = "https://twitter.com/mkrms_again" class="fab fa-twitter-square fa-3x text-white float-right"></a>
      </div>
        <p class ="text-center text-white">Niiyama keisuke</p>
    </div>
  </footer>

app/views/homes/index.html.erb
<% if user_signed_in? %>
<%= render "login"%>
<% else %>
<%= render "not-login"%>
<% end %>

<footer class ="bg-dark">
    <div class ="container">
      <div class ="col-md-6 mx-auto text-white pb-5 pt-3 mt-3">
        <li>
          <%= link_to '利用規約', about_homes_path, class: 'text-white pr-3'%>
        </li>
        <% if current_user.try(:admin?) %>
          <li>
            <%= link_to '管理者ページ', rails_admin_path, class: 'text-white pr-3'%>
          </li>
        <% end %>
        <li>
          お問い合わせはTwitterのDMまで
        </li>
        <a href = "https://twitter.com/mkrms_again" class="fab fa-twitter-square fa-3x text-white float-right"></a>
      </div>
        <p class ="text-center text-white">Niiyama keisuke</p>
    </div>
  </footer>