config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'homes#index'
  resources :homes do
    collection do
      get 'about'
      get 'howto'
    end
  end
  resources :tasks
  
  resources :homeworks do
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/homework.rb
class Homework < ApplicationRecord
    belongs_to :user
    belongs_to :course
    has_many :comments
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_homework, only: [:show, :edit, :update, :destroy]
  def index
    @homework = current_user.course.homeworks.all
  end

  def show
    @comments = @homework.comments
    @comment = current_user.comments.new
  end

  def edit
  end

  def new
    @homework = Homework.new
    @course = current_user.course
  end

  def create
    @homework = Homework.new(homework_params)
    @homework.course_id = current_user.course_id
    @homework.user_id = current_user.id
    if @homework.save!
      redirect_to homeworks_path, notice: '作成できました'
    else
      render :new, alert: '作成できませんでした'
    end
  end

  def update
    if @homework.update(homework_params)
      redirect_to homeworks_path, notice: '更新できました'
    else
      render :show, alert: '更新できませんでした'
    end
  end

  def destroy
    if @homework.destroy
      redirect_to homeworks_path, notice: '削除しました'
    else
      redirect_to homeworks_path, alert: '削除に失敗しました'
    end
  end

  private
    def set_homework
      @homework = Homework.find(params[:id])
    end

    def homework_params
      params.require(:homework).permit(:memo, :subject, :content, :deadline)
    end
end

app/views/homeworks/edit.html.erb
<div class = "container mt-3">
    <div class = "col-md-8 mx-auto">
    <%= form_for (@homework) do |f| %>
        <div class = "card container pt-3">
            <%= f.hidden_field :course_id, value: current_user.course_id %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            
            <div class = "form-group">
                <div class = "form-group row">
                    <%= f.label '教科：', class: 'col-md-2'%>
                    <%= f.text_field :subject, class: 'form-control col-md-6'%>
                </div>

                <div class = "form-group row">
                    <%= f.label '課題内容：', class: 'col-md-2'%>
                    <%= f.text_field :content, class: 'form-control col-md-6'%>
                </div>

                <div class = "form-group row">
                    <%= f.label '締め切り：', class: 'col-md-2'%>
                    <%= f.date_select :deadline, use_month_numbers:true, prompt:"--", start_year:Time.now.year, class: 'form-control col-md-6'%>
                </div>

                <div class = "form-group row">
                    <%= f.label '説明：', class: 'col-md-2'%>
                    <%= f.text_area :memo, class: 'form-control col-md-6'%>
                </div>
            </div>
        </div>
        <%= f.submit "課題登録", class:'btn btn-success float-right my-3'%>
    <%end%>
    </div>
</div>

app/views/homeworks/index.html.erb
<h2 class ="text-center">[課題管理]</h2>
<div class ="container">
<div class ="table-responsive text-nowrap">
    <%= link_to "新規作成", new_homework_path, class: "btn btn-primary mb-3 float-right" %>
    <ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="item1-tab" data-toggle="tab" href="#item1" role="tab" aria-controls="item1" aria-selected="true"><div class = "ml-3">課題一覧</div></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="item2-tab" data-toggle="tab" href="#item2" role="tab" aria-controls="item2" aria-selected="false"><div class = "ml-3">締切前</div></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="item3-tab" data-toggle="tab" href="#item3" role="tab" aria-controls="item3" aria-selected="false"><div class = "ml-3">締切超過</div></a>
  </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade show active text-center" id="item1" role="tabpanel" aria-labelledby="item1-tab">
                <table class = "table table-bordered">
                    <thead class = "thead-light">
                        <tr>
                            <th>教科</th>
                            <th>課題内容</th>
                            <th>締め切り</th>
                            <th>作成者</th>
                            <th>コメント</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @homework.each do |homework| %>
                            <tr>
                                <td><%= homework.subject %></td>
                                <td><%= homework.content %></td>
                                <% if homework.deadline.present?%>

                                    <% if Date.today < homework.deadline %>
                                        <td> <%= homework.deadline%> </td>
                                    <%elsif Date.today > homework.deadline %>
                                        <td class ="text-danger"> <%= homework.deadline %> </td>
                                    <% else %>
                                        <td class = "text-success"> <%= homework.deadline %> </td>
                                    <% end %>

                                <% else %>
                                    <td></td>
                                <%end%>
                                    <td><%= homework.user.name %></td>
                                    <td><%= homework.comments.count%></td>
                                    <td><%= link_to '',  homework, class: 'fas fa-edit fa-2x text-dark'%></td>
                            </tr>
                        <% end %>

                    </tbody>
                </table>
        </div>
        <div class="tab-pane fade text-center" id="item2" role="tabpanel" aria-labelledby="item2-tab">
            <table class = "table table-bordered">
                <thead class = "thead-light">
                    <tr>
                        <th>教科</th>
                        <th>課題内容</th>
                        <th>締め切り</th>
                        <th>作成者</th>
                        <th>コメント</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @homework.each do |homework| %>
                        <% if homework.deadline.present? %>
                            <% if Date.today <= homework.deadline%>
                            <tr>
                                <td><%= homework.subject %></td>
                                <td><%= homework.content %></td>
                                <% if homework.deadline.present?%>

                                    <% if Date.today < homework.deadline %>
                                        <td> <%= homework.deadline%> </td>
                                    <%elsif Date.today > homework.deadline %>
                                        <td class ="text-danger"> <%= homework.deadline %> </td>
                                    <% else %>
                                        <td class = "text-success"> <%= homework.deadline %> </td>
                                    <% end %>

                                <% else %>
                                    <td></td>
                                <%end%>
                                    <td><%= homework.user.name %></td>
                                    <td><%= homework.comments.count%></td>
                                    <td><%= link_to '',  homework, class: 'fas fa-edit fa-2x text-dark'%></td>
                            </tr>
                            <% end %>
                        <% end %>
                    <% end%>

                </tbody>
            </table>
        </div>
        <div class="tab-pane fade text-center" id="item3" role="tabpanel" aria-labelledby="item3-tab">
            <table class = "table table-bordered">
                <thead class = "thead-light">
                    <tr>
                        <th>教科</th>
                        <th>課題内容</th>
                        <th>締め切り</th>
                        <th>作成者</th>
                        <th>コメント</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @homework.each do |homework| %>
                        <% if homework.deadline.present? %>
                            <% if Date.today > homework.deadline%>
                            <tr>
                                <td><%= homework.subject %></td>
                                <td><%= homework.content %></td>
                                <% if homework.deadline.present?%>

                                    <% if Date.today < homework.deadline %>
                                        <td> <%= homework.deadline%> </td>
                                    <%elsif Date.today > homework.deadline %>
                                        <td class ="text-danger"> <%= homework.deadline %> </td>
                                    <% else %>
                                        <td class = "text-success"> <%= homework.deadline %> </td>
                                    <% end %>

                                <% else %>
                                    <td></td>
                                <%end%>
                                    <td><%= homework.user.name %></td>
                                    <td><%= homework.comments.count%></td>
                                    <td><%= link_to '',  homework, class: 'fas fa-edit fa-2x text-dark'%></td>
                            </tr>
                            <% end %>
                        <% end %>
                    <% end %>

                </tbody>
            </table>
        </div>
    </div>
</div>
            </div>

app/views/homeworks/new.html.erb
<div class = "container mt-3">
    <div class = "col-md-8 mx-auto">
    <%= form_for (@homework) do |f| %>
        <div class = "card container pt-3">
            <%= f.hidden_field :course_id, value: current_user.course_id %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            
            <div class = "form-group">
                <div class = "form-group row">
                    <%= f.label '教科：', class: 'col-md-2'%>
                    <%= f.text_field :subject, class: 'form-control col-md-6'%>
                </div>

                <div class = "form-group row">
                    <%= f.label '課題内容：', class: 'col-md-2'%>
                    <%= f.text_field :content, class: 'form-control col-md-6'%>
                </div>

                <div class = "form-group row">
                    <%= f.label '締め切り：', class: 'col-md-2'%>
                    <%= f.date_select :deadline, use_month_numbers:true, prompt:"--", start_year:Time.now.year, class: 'form-control col-md-6'%>
                </div>

                <div class = "form-group row">
                    <%= f.label '説明：', class: 'col-md-2'%>
                    <%= f.text_area :memo, class: 'form-control col-md-6'%>
                </div>
            </div>
        </div>
        <%= f.submit "課題登録", class:'btn btn-success float-right my-3'%>
    <%end%>
    </div>
</div>

app/views/homeworks/show.html.erb
<div class = "col-md-6 mx-auto px-3 py-2">
<ul class = "h5" style ="line-height:2.5rem;">
    <li> 教科：<%= @homework.subject %></li>
    <li> 内容：<%= @homework.content %></li>
    <li> 説明：<%= @homework.memo %></li>
    <li>締切：<%= @homework.deadline%></li>
</ul>

    <% if current_user == @homework.user %>
        <div class ="mt-3">
        <%= link_to "編集", edit_homework_path, class: 'btn btn-success float-right ml-3'%>
        <%= link_to "削除", homework_path(@homework), method: :delete, data: {confirm: "本当に削除しますか？"}, class: 'btn btn-danger float-right'%>
        </div>
    <% end %>

    <%= form_for [@homework, @comment] do |c| %>
        <div class ="pt-5">
        <%= c.text_area :comment_content, class: 'form-control mt-3'%>
        <%= c.hidden_field :homework_id, value:@homework.id %>
        <%= c.hidden_field :user_id, value:current_user.id %>
        <%= c.submit "コメント送信", class:'btn btn-success float-right mt-3 mb-3'%>
        </div>
    <% end %>

    <table class="table">
    <thead>
        <tr>
        <th>コメント</th>
        <th>送信者</th>
        <th>　　</th>
        </tr>
    </thead>

    <% @comments.each do |comment| %>
        <tr>
        <td><%= comment.comment_content%></td>
        <td><%= comment.user.name%></td>
        <td>
        <% if current_user == comment.user %>
            <%= link_to "削除", homework_comment_path(@homework, comment), method: :delete%>
        <% end %>
        </td>
        </tr>
    <% end %>
    </table>
</div>