config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'homes#index'
  resources :homes do
    collection do
      get 'about'
      get 'howto'
    end
  end
  resources :tasks
  
  resources :homeworks do
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability
  
  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :homework
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :users
    has_many :homeworks
    has_many :subjects
end

app/models/homework.rb
class Homework < ApplicationRecord
    belongs_to :user
    belongs_to :course
    has_many :comments
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :course
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
  has_many :homeworks, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :course
  validates :name, format: {with: /\A[hr]\d{2}[mecz]\d{2}\z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @homework = Homework.find(params[:homework_id])
        @comment = current_user.comments.new(comment_params)
        @comment.user_id = current_user.id

        if @comment.save!
        redirect_back(fallback_location: root_path)
        else
        redirect_back(fallback_location: root_path)
        end
    end

    def destroy
        @comment = Comment.find(params[:id])
        if @comment.destroy
            redirect_back(fallback_location: root_path)       
        else
            redirect_back(fallback_location: root_path)       
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:comment_content, :homework_id, :user_id) 
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_homework, only: [:show, :edit, :update, :destroy]
  def index
    @homework = current_user.course.homeworks.all
  end

  def show
    @comments = @homework.comments
    @comment = current_user.comments.new
  end

  def edit
  end

  def new
    @homework = Homework.new
    @course = current_user.course
  end

  def create
    @homework = Homework.new(homework_params)
    @homework.course_id = current_user.course_id
    @homework.user_id = current_user.id
    if @homework.save!
      redirect_to homeworks_path, notice: '作成できました'
    else
      render :new, alert: '作成できませんでした'
    end
  end

  def update
    if @homework.update(homework_params)
      redirect_to homeworks_path, notice: '更新できました'
    else
      render :show, alert: '更新できませんでした'
    end
  end

  def destroy
    if @homework.destroy
      redirect_to homeworks_path, notice: '削除しました'
    else
      redirect_to homeworks_path, alert: '削除に失敗しました'
    end
  end

  private
    def set_homework
      @homework = Homework.find(params[:id])
    end

    def homework_params
      params.require(:homework).permit(:memo, :subject, :content, :deadline)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:show, :edit, :update, :destroy]

  def index
    @task = current_user.tasks.all
  end

  def show
  end

  def edit
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to tasks_path, notice: '作成できました'
    else
      render :new, alert: '作成できませんでした'
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: '更新できました'
    else
      render :show, alert: '更新できませんでした'
    end
  end

  def destroy
    if @task.destroy
      redirect_to tasks_path, notice: '削除しました'
    else
      redirect_to tasks_path, alert: '削除に失敗しました'
    end
  end

  def about
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :body, :deadline)
    end

    def validate_user
      if @task.user != current_user
        redirect_to root_path, alert: "自分のタスクではありません"
      end
    end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/borders_helper.rb
module BordersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
      return '' if resource.errors.empty?
  
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
      sentence = I18n.t('errors.messages.not_saved',
        count: resource.errors.count,
        resource: resource.class.model_name.human.downcase)
  
      html = <<-HTML
      <div class="alert alert-error alert-block">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>
            <h4>#{sentence}</h4>
        </strong>
        #{messages}
        
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      </div>
      HTML
  
      html.html_safe
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kosen-Manager</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
      <% if user_signed_in? %>
      <a href="/" class="navbar-brand anton"><%= current_user.course.course_name%> Manager</a>
      <% else %>
       <a href="/" class="navbar-brand anton">Kosen Manager</a>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
      menu
      <span class="navbar-toggler-icon"></span>
    </button>

        <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto ml-5">
        <li class="nav-item">
          <%= link_to 'Top', root_path, class: 'text-white pr-3'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Todo', tasks_path, class: 'text-white pr-3'%>
        </li>

        <li class="nav-item">
          <%= link_to '課題管理', homeworks_path, class: 'text-white pr-3'%>
        </li>

        <li class="nav-item">
          <%= link_to '使い方', howto_homes_path, class: 'text-white pr-3'%>
        </li>

        <%# <li class="nav-item"> <%= link_to 'BlackBoard', "https://bb.kosen-ac.jp/", class: 'text-white pr-3' </li>%>
      </ul>

        <div class = "float-right">
            <% if user_signed_in? %>
                <%= link_to 'マイページ', edit_user_registration_path, class: 'btn bg-dark text-white mr-3' %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn bg-dark text-white mr-3' %>
            <% else %>
                <%= link_to 'サインアップ', new_user_registration_path, class: 'btn bg-light text-dark mr-3' %>
                <%= link_to 'ログイン', new_user_session_path, class: 'btn bg-dark text-white mr-3' %>
            <% end %>
        </div>
    </nav>

    <% flash.each do |key, value|%>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>
            <%= content_tag(:div, value, class: "#{key}") %>
        </strong>
        
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>